#!/bin/bash

# for this to work you must configure sudo such that it will be able to run the command without password

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# .. more yabai startup stuff

# bsp or float (default: float)
yabai -m config layout bsp

# Override default layout for space 2 only
# yabai -m config --space 2 layout float

# Duration of window frame animation. If 0.0, the change in dimension is not animated.
# yabai -m config window_animation_duration 0.0

# Set all padding and gaps to 20pt (default: 0)
# yabai -m config top_padding    4
# yabai -m config bottom_padding 4
# yabai -m config left_padding   4
# yabai -m config right_padding  4
# yabai -m config window_gap     3

yabai -m config top_padding 10
yabai -m config bottom_padding 20
yabai -m config left_padding 20
yabai -m config right_padding 20
yabai -m config window_gap 10

# add 20 padding to the top and 0 padding to the bottom of every space located on the main display
# yabai -m config external_bar main:20:0
# add padding to the top and bottom of all spaces regardless of the display it belongs to
yabai -m config external_bar all:26:0

# Override gaps for space 2 only
# yabai -m config --space 2 window_gap 0

# Auto balance makes it so all windows always occupy the same space, independent of how deeply nested they are in the
# window tree. When a new window is inserted or a window is removed, the split ratios will be automatically adjusted.
# on or off (default: off)
yabai -m config auto_balance off

# The split ratio defines how much space each window occupies after a new split is created. A value of 0.5 means that
# both old and new window occupy the same space; a value of 0.2 means that the old window occupies 20% of the available
# space and the new window occupies 80% of the available space. New windows are inserted at the right or bottom side.
# The ratio needs to be between 0 and 1.
# Auto balance overrides your split ratio configuration and makes it so all windows always occupy the same space,
# independent of how deeply nested they are in the window tree. When a new window is inserted or a window is removed,
# the split ratios will be automatically adjusted.
yabai -m config split_ratio 0.7

# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier fn

# set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse off

# set mouse follows focus mode (default: off)
yabai -m config mouse_follows_focus off

# floating windows are always on top (default: off)
yabai -m config window_topmost off

# modify window shadows (default: on, options: on, off, float)
# example: show shadows only for floating windows
# yabai -m config window_shadow float
yabai -m config window_shadow float

# window opacity (default: off)
# example: render all unfocused windows with 90% opacity
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.95

yabai -m config window_border off
yabai -m config window_border_radius 6
yabai -m config window_border_hidpi off
yabai -m config window_border_blur off
yabai -m config window_border_width 1
yabai -m config active_window_border_color 0xFFB3E5FC # Light blue
# yabai -m config active_window_border_color 0xFF5DADE2 # Slightly darker blue
# yabai -m config active_window_border_color 0xFFFFECB3 # Yellow
# yabai -m config active_window_border_color 0xFFA8D17F # Green
# yabai -m config active_window_border_color 0xFFFFDEDE # Light pink
# Transparent color
yabai -m config normal_window_border_color 0x00FFECB3

# rules
yabai -m rule --add app=".*"
## makes system preferences always floating
yabai -m rule --add app="^Stats$" manage=off
yabai -m rule --add app="^Snipaste$" manage=off
yabai -m rule --add app="^python$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Inkscape$" title="^新增图层$" manage=off
yabai -m rule --add app="^Google Chrome$" title="画中画" manage=off
yabai -m rule --add app="^访达$" title="简介$" manage=off
yabai -m rule --add app="^访达$" title="快速查看$" manage=off
yabai -m rule --add app='^Arc$' title='^Space.*$' manage=off
yabai -m rule --add app="^访达$" manage=off grid=10:10:1:1:8:8

yabai -m rule --add app="^kitty$" title="^nvim_" manage=off grid=10:10:2:1:6:4

yabai -m rule --add app="^微信$" title!="^微信$" manage=off
yabai -m rule --add app="^微信$" title="^微信$" manage=off grid=10:10:1:1:8:8

# Match non-major window of Inkscape, something like "文件名已存在，你要替换它吗?" floating window
yabai -m rule --add app="^Inkscape$" title="^$" manage=off

yabai -m rule --add app="^Godot$" manage=off

yabai -m rule --add app="^系统设置$" manage=off grid=10:10:1:1:8:8
# yabai -m rule --add app="^Steam$" manage=off grid=10:10:1:1:8:8
yabai -m rule --add app="^MacZip$" manage=off grid=10:10:1:1:8:8
yabai -m rule --add app="^邮件$" manage=off grid=10:10:1:1:8:8
yabai -m rule --add app="^网易云音乐$" manage=off grid=10:10:1:1:8:8
yabai -m rule --add app="^WeChat$" manage=off grid=10:10:1:1:8:8
yabai -m rule --add app="^飞书$" manage=off grid=10:10:1:1:8:8
# yabai -m rule --add app="^飞书会议$" manage=off
yabai -m rule --add app="^Clash Verge$" manage=off grid=10:10:1:1:8:8
yabai -m rule --add app="^备忘录$" manage=off grid=10:10:1:1:8:8
yabai -m rule --add app="^天气$" manage=off grid=10:10:1:1:8:8
yabai -m rule --add app="^欧路词典$" manage=off grid=10:10:1:1:8:8

# Added window borders: https://github.com/FelixKratz/JankyBorders
# borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 2>/dev/null 1>&2 &
# borders active_color="gradient(top_left=0xffe1e3e4,bottom_right=0xfff6cefc)" inactive_color=0xff494d64 width=3.0 hidpi=on 2>/dev/null 1>&2 &

echo "yabai configuration loaded.."
